### ISSUE TITLE
Update the project

### ISSUE THREAD

**Issue by ghost** [gibbok/react-color-picker-palette#1]
I'm trying to implement your color picker, but it's deprecated in some dependencies. I left you the screenshot of that

![screenshot_1](https://user-images.githubusercontent.com/32103862/34133729-0180a6f2-e41c-11e7-912b-ec22d3f128e3.png)

If I implement the picker in my project, I get this error related with Babel (maybe because of the outdate dependency):

![screenshot_2](https://user-images.githubusercontent.com/2947307/34133794-682cbb98-e41c-11e7-9198-2f6bd4cf0f2d.png)

Also: Does the picker has functions to get the values of the colors?

Thanks

**Comment by gibbok** [comment]
Hi I just release a new version which can solve your issue, please check it out. Thanks!

https://github.com/gibbok/react-color-picker-palette

https://gibbok.github.io/react-color-picker-palette/?path=/story/*
