### ISSUE TITLE
Canvas width is ignored

### ISSUE THREAD

**Issue by huhonator** [gibbok/react-color-picker-palette#4]
Hi, I have overrode default style, to be specific the canvas width and it's being ignored in term of creating colour gradients in JS. The canvas width in html is set correctly, but in calculating process of gradient offsets it gets the default value. The outcome of this: you get wrong colour value in onSelectColor

**Comment by gibbok** [comment]
Hi, could you please provide a sample of your code? So I can try to reproduce this issue?
Thanks

**Comment by gibbok** [comment]
Bug has been fixed, works now well in Chrome and FireFox. Thanks for reporting it :)
https://github.com/gibbok/react-color-picker-palette/issues/4
